---
- name: Install prerequisites for Debian
  apt:
          name: gpg,python-pexpect,python3-pexpect
          state: present
  register: apt_prereq_result
  until: apt_prereq_result is success
  retries: 10
  delay: 2

- name: Setup repository key from keyserver
  apt_key:
          keyserver: "{{ opensips_apt_key_server }}"
          id: "{{ opensips_apt_key_id }}"
  register: apt_key_result
  until: apt_key_result is success
  retries: 10
  delay: 2

- name: Add opensips-cli repo
  apt_repository:
          repo: "{{ debian_repo_fetch }}"
          state: present

- name: Install opensips-cli
  apt:
          name: opensips-cli
  register: apt_install_result
  until: apt_install_result is success
  retries: 10
  delay: 2

- name: Create database user with name 'opensips' and password 'opensipsrw' with all database privileges
  community.mysql.mysql_user:
    name: opensips
    login_unix_socket: /var/lib/mysql/mysql.sock
#    login_user: "{{ opensips_cp_db_user }}"
#    login_password: "{{ opensips_cp_db_pass }}"
    password: opensipsrw
    priv: 'opensips.*:ALL'
    state: present
  when: ansible_os_family == "RedHat"


- name: Create database user with name 'opensips' and password 'opensipsrw' with all database privileges
  community.mysql.mysql_user:
    name: opensips
    login_unix_socket: /var/run/mysqld/mysqld.sock
#    login_user: "{{ opensips_cp_db_user }}"
#    login_password: "{{ opensips_cp_db_pass }}"
    password: opensipsrw
    priv: 'opensips.*:ALL'
    state: present
  when: ansible_os_family == "Debian"


- name: Create Database for opensips
  expect:
    command: /bin/bash -c "opensips-cli -x database create opensips"
    responses:
      (?i)Password: "\n"
